[tool.poetry]
name = "cheating-based-prompt-engine"
version = "0.1.0"
description = "A brief description of your project"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
antlr4-python3-runtime = "4.13.2"
certifi = "2024.8.30"
charset-normalizer = "3.4.0"
colorama = "0.4.6"
et-xmlfile = "1.1.0"
idna = "3.10"
joblib = "1.4.2"
numpy = "1.24.4"
openpyxl = "3.1.5"
pandas = "2.0.3"
psycopg2-binary = "2.9.9"
python-dateutil = "2.9.0.post0"
python-dotenv = "1.0.1"
pytz = "2024.2"
requests = "2.32.3"
scikit-learn = "1.3.2"
scipy = "1.10.1"
simplejson = "3.19.3"
six = "1.16.0"
SQLAlchemy = "2.0.35"
threadpoolctl = "3.5.0"
tqdm = "4.66.5"
typing_extensions = "4.12.2"
tzdata = "2024.2"
urllib3 = "2.2.3"
python-dotenv = "1.0.1"

[tool.poetry.group.full]
optional = true


[tool.poetry.group.full.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"